// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"user_list/models"
)

// FindUserByIDOKCode is the HTTP code returned for type FindUserByIDOK
const FindUserByIDOKCode int = 200

/*FindUserByIDOK user response

swagger:response findUserByIdOK
*/
type FindUserByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewFindUserByIDOK creates FindUserByIDOK with default headers values
func NewFindUserByIDOK() *FindUserByIDOK {

	return &FindUserByIDOK{}
}

// WithPayload adds the payload to the find user by Id o k response
func (o *FindUserByIDOK) WithPayload(payload *models.User) *FindUserByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find user by Id o k response
func (o *FindUserByIDOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindUserByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FindUserByIDDefault unexpected error

swagger:response findUserByIdDefault
*/
type FindUserByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindUserByIDDefault creates FindUserByIDDefault with default headers values
func NewFindUserByIDDefault(code int) *FindUserByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &FindUserByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find user by id default response
func (o *FindUserByIDDefault) WithStatusCode(code int) *FindUserByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find user by id default response
func (o *FindUserByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find user by id default response
func (o *FindUserByIDDefault) WithPayload(payload *models.Error) *FindUserByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find user by id default response
func (o *FindUserByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindUserByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
