{
 "title": "Main Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency quantile 0.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket{exported_endpoint!=\"/metrics\"}[1m]))\n) * 1000\n",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency quantile 0.95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket{exported_endpoint!=\"/metrics\"}[1m]))\n) * 1000\n",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency quantile 0.99 ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket{exported_endpoint!=\"/metrics\"}[1m]))\n) * 1000",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency quantile max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket{exported_endpoint!=\"/metrics\"}[1m]))\n) * 1000",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Application Request Count (RPS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count{exported_endpoint!=\"/metrics\"}[1m]))",
     "legendFormat": "RPS {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Error Rare",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count{exported_endpoint!=\"/metrics\",http_status=~\"5.+\"}[1m]))",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  }
 ]
}