{
 "title": "NGINX Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency quantile 0.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, path) \n         (rate(nginx_ingress_controller_response_duration_seconds_bucket{path=\"/otusapp/borisershov/api/v1(/|$)(.*)\"}[1m]))\n) * 1000\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency quantile 0.95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, path) \n         (rate(nginx_ingress_controller_response_duration_seconds_bucket{path=\"/otusapp/borisershov/api/v1(/|$)(.*)\"}[1m]))\n) * 1000\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency quantile 0.99 ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, path) \n         (rate(nginx_ingress_controller_response_duration_seconds_bucket{path=\"/otusapp/borisershov/api/v1(/|$)(.*)\"}[1m]))\n) * 1000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency quantile max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, \n      sum by (le, path) \n         (rate(nginx_ingress_controller_response_duration_seconds_bucket{path=\"/otusapp/borisershov/api/v1(/|$)(.*)\"}[1m]))\n) * 1000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Application Request Count (RPS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "RPS {{path}}"
    }
   ]
  },
  {
   "title": "Error Rare",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}