// Code generated by go-swagger; DO NOT EDIT.

package healthcheck

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"user_list/models"
)

// ReadinessHealthCheckOKCode is the HTTP code returned for type ReadinessHealthCheckOK
const ReadinessHealthCheckOKCode int = 200

/*ReadinessHealthCheckOK Success

swagger:response readinessHealthCheckOK
*/
type ReadinessHealthCheckOK struct {

	/*
	  In: Body
	*/
	Payload *models.HealthCheckStatus `json:"body,omitempty"`
}

// NewReadinessHealthCheckOK creates ReadinessHealthCheckOK with default headers values
func NewReadinessHealthCheckOK() *ReadinessHealthCheckOK {

	return &ReadinessHealthCheckOK{}
}

// WithPayload adds the payload to the readiness health check o k response
func (o *ReadinessHealthCheckOK) WithPayload(payload *models.HealthCheckStatus) *ReadinessHealthCheckOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the readiness health check o k response
func (o *ReadinessHealthCheckOK) SetPayload(payload *models.HealthCheckStatus) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReadinessHealthCheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ReadinessHealthCheckDefault unexpected error

swagger:response readinessHealthCheckDefault
*/
type ReadinessHealthCheckDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReadinessHealthCheckDefault creates ReadinessHealthCheckDefault with default headers values
func NewReadinessHealthCheckDefault(code int) *ReadinessHealthCheckDefault {
	if code <= 0 {
		code = 500
	}

	return &ReadinessHealthCheckDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the readiness health check default response
func (o *ReadinessHealthCheckDefault) WithStatusCode(code int) *ReadinessHealthCheckDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the readiness health check default response
func (o *ReadinessHealthCheckDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the readiness health check default response
func (o *ReadinessHealthCheckDefault) WithPayload(payload *models.Error) *ReadinessHealthCheckDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the readiness health check default response
func (o *ReadinessHealthCheckDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReadinessHealthCheckDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
