# Source: userlist/templates/jobs.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: userlist-migrate
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "10"
spec:
  activeDeadlineSeconds: 60
  backoffLimit: 0
  template:
    metadata:
      name: userlist-migrate
    spec:       
      containers:
        - name: job
          image: wwtlf/user_list_migrate:0.1
          command: ["migrate", "-database", "${POSTGRESQL_URL}", "-path" , "migrations", "up"]
          imagePullPolicy: IfNotPresent          
          env:
            - name: "POSTGRESQL_HOSTNAME"
              valueFrom:
                configMapKeyRef:
                    name: test-userlist-configmap
                    key: POSTGRESQL_HOSTNAME
            - name: "POSTGRESQL_URL"
              valueFrom:
                configMapKeyRef:
                    name: test-userlist-configmap
                    key: POSTGRESQL_URL
    
            - name: "POSTGRESQL_PORT_NUMBER"
              valueFrom:
                configMapKeyRef:
                  name: test-userlist-configmap
                  key: POSTGRESQL_PORT_NUMBER
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: test-userlist-secret
                  key: POSTGRES_USER
            - name: "POSTGRES_PASSWORD"            
              valueFrom:
                secretKeyRef:
                  name: test-userlist-secret
                  key: POSTGRES_PASSWORD
            - name: "PGPASSWORD"
              valueFrom:
                secretKeyRef:
                    name: test-pg
                    key: postgresql-password
      restartPolicy: Never