apiVersion: v1
kind: Service
metadata:
  name: userlist-service
spec:
  type: NodePort
  selector:
    app: userlist
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32080