// Code generated by go-swagger; DO NOT EDIT.

// Package restapi User Service
//
//  This is simple client API
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.1
//  Contact: <schetinnikov@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
